public static $chartOfAccountSubType = array(
        "assets" => array(
            '1' => 'Current Asset',
            '2' => 'Inventory Asset',
            '3' => 'Non-current Asset',
            '4' => 'Machinery Asset',
            '5' => 'Transport Asset',
        ),
        "liabilities" => array(
            '1' => 'Current Liabilities',
            '2' => 'Long Term Liabilities',
            '3' => 'Share Capital',
            '4' => 'Retained Earnings',
        ),
        "equity" => array(
            '1' => 'Owners Equity',
            '2' => 'Investors Equity',
        ),
        "income" => array(
            '1' => 'Sales Revenue',
            '2' => 'Other Revenue',
            '3' => 'Project Revenue',
        ),
        "costs of goods sold" => array(
            '1' => 'Costs of Goods Sold',
        ),
        "expenses" => array(
            '1' => 'Payroll Expenses',
            '2' => 'General and Administrative expenses',
        ),
        "construction expenses" => array(
            '1' => 'Costs of Goods Purchase',
            '2' => 'Maintenance and Repair',
            '3' => 'Engineering and HRM',
            '4' => 'Head Office Expense',
            '5' => 'Travel and Allowances',
        ),
        "construction materials" => array(
            '1' => 'Structural Materials',
            '2' => 'Pavement Materials',
            '3' => 'Other Materials',
            '4' => 'Additional Considerations',
            '5' => 'Maintenance and Repair',
            '6' => 'Engineering',
        ),
        "construction mecineries" => array(
            '1' => 'Earthmoving and Excavation',
            '2' => 'Material Handling',
            '3' => 'Compaction',
            '4' => 'Concrete Work',
            '5' => 'Road Construction',
            '6' => 'Demolition',
            '7' => 'Other Equipment',
            '8' => 'Engineering and Maintenance',
            '9' => 'Transport and Garage',
        ),
        "construction vehicles" => array(
            '1' => 'Earthmoving and Transport',
            '2' => 'Excavation and Material Handling',
            '3' => 'Compaction and Paving',
            '4' => 'Concrete Work',
            '5' => 'Support Vehicles',
            '6' => 'Specialized Vehicles',
            '7' => 'Other Vehicles',
            '8' => 'Engineering and Maintenance',
            '9' => 'Transport and Garage',
        ),
        "site expenses" => array(
            '1' => 'Costs of Living',
            '2' => 'Maintenance and Repair',
            '3' => 'Engineering and HRM',
            '4' => 'Site Office Expense',
            '5' => 'Travel and Allowances',
            '6' => 'Site Advance',
            '7' => 'Site Expense',
            '8' => 'Site Income',
            '9' => 'Foods and Snacks',
        ),
    );